/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nox;

/**
 *
 * @author Vam
 */
public class Booking_Confirmation extends javax.swing.JFrame {

    /**
     * Creates new form Booking_Confirmation
     */
    public int totalfare;
    public Booking_Confirmation() {
        initComponents();
        MOP_Label.setVisible(false);
        MOP_ComboBox.setVisible(false);
        Proceed_Button.setVisible(false);
        CYB_Label.setVisible(false);
        CYB_ComboBox.setVisible(false);
        CardNo_Label.setVisible(false);
        CardNo_TextField.setVisible(false);
        Name_Label.setVisible(false);
        Name_TextField.setVisible(false);
        Valid_Label.setVisible(false);
        Valid_ComboBox.setVisible(false);
        PIN_Label.setVisible(false);
        PIN_PasswordField.setVisible(false);
        Pay_Button.setVisible(false);
        Message_Label.setVisible(false);
        
        totalfare = Book_Tickets.fare;
        jLabel12.setText(""+totalfare+" ");
        jLabel12.setVisible(true);
        jLabel13.setText(""+Book_Tickets.movie+" ");
        jLabel4.setText(""+Book_Tickets.no_tickets);
        jLabel8.setText(""+Book_Tickets.seats+" ");
        jLabel14.setText(""+Book_Tickets.date+"");
        jLabel10.setText(""+Book_Tickets.show_time+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        MOP_Label = new javax.swing.JLabel();
        MOP_ComboBox = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        CYB_Label = new javax.swing.JLabel();
        CYB_ComboBox = new javax.swing.JComboBox();
        Proceed_Button = new javax.swing.JButton();
        CardNo_Label = new javax.swing.JLabel();
        CardNo_TextField = new javax.swing.JTextField();
        Name_Label = new javax.swing.JLabel();
        Name_TextField = new javax.swing.JTextField();
        Valid_Label = new javax.swing.JLabel();
        Valid_ComboBox = new javax.swing.JComboBox();
        PIN_Label = new javax.swing.JLabel();
        PIN_PasswordField = new javax.swing.JPasswordField();
        Pay_Button = new javax.swing.JButton();
        Message_Label = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Selected Movie");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("No. of Tickets");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Seats");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Date");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Show Time");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Total Fare");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        MOP_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        MOP_Label.setForeground(new java.awt.Color(204, 204, 204));
        MOP_Label.setText("Select Mode of Payment");

        MOP_ComboBox.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        MOP_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Debit Card", "Net Banking", "Credit Card" }));

        jButton3.setText("<< Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        CYB_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        CYB_Label.setForeground(new java.awt.Color(204, 204, 204));
        CYB_Label.setText("Choose your Bank");

        CYB_ComboBox.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        CYB_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "State Bank of India", "HDFC", "Allahabad Bank", "Royal Bank of Scotland", "Punjab National Bank", "Swiss Bank" }));

        Proceed_Button.setText("Next");
        Proceed_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proceed_ButtonActionPerformed(evt);
            }
        });

        CardNo_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        CardNo_Label.setForeground(new java.awt.Color(204, 204, 204));
        CardNo_Label.setText("Enter your Card No.");

        CardNo_TextField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N

        Name_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Name_Label.setForeground(new java.awt.Color(204, 204, 204));
        Name_Label.setText("Name on Card");

        Name_TextField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N

        Valid_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Valid_Label.setForeground(new java.awt.Color(204, 204, 204));
        Valid_Label.setText("Valid Upto");

        Valid_ComboBox.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Valid_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "May, 2013", "May, 2014", "May, 2015", "May, 2016", "May, 2017", "May, 2018", "May, 2019", "May, 2020", "May, 2021", "May, 2022", "May, 2023" }));

        PIN_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        PIN_Label.setForeground(new java.awt.Color(204, 204, 204));
        PIN_Label.setText("PIN");

        Pay_Button.setText("Pay");
        Pay_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pay_ButtonActionPerformed(evt);
            }
        });

        Message_Label.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        Message_Label.setForeground(new java.awt.Color(204, 204, 204));
        Message_Label.setText("* Transaction Successful");

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("jLabel13");

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jButton1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(76, 76, 76)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 457, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Message_Label)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Pay_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Proceed_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(MOP_Label)
                                        .addComponent(CYB_Label)
                                        .addComponent(CardNo_Label)
                                        .addComponent(Name_Label)
                                        .addComponent(Valid_Label)
                                        .addComponent(PIN_Label))
                                    .addGap(72, 72, 72)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(MOP_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CYB_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CardNo_TextField)
                                        .addComponent(Name_TextField)
                                        .addComponent(Valid_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PIN_PasswordField)))))
                        .addGap(97, 97, 97))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(MOP_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MOP_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CYB_Label)
                            .addComponent(CYB_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CardNo_Label)
                    .addComponent(CardNo_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name_Label)
                    .addComponent(Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Valid_Label)
                    .addComponent(Valid_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(20, 20, 20)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PIN_Label)
                    .addComponent(PIN_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(Proceed_Button)
                    .addComponent(Pay_Button))
                .addGap(35, 35, 35)
                .addComponent(Message_Label)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nox/cinemas/Background/Book tickets.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MOP_Label.setVisible(true);
        MOP_ComboBox.setVisible(true);
        Proceed_Button.setVisible(true);
        CYB_Label.setVisible(true);
        CYB_ComboBox.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Proceed_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proceed_ButtonActionPerformed
        String Bank = "Debit Card";
        String Bank2 = "Credit Card";
        if(MOP_ComboBox.getSelectedItem().toString().equals(Bank) || MOP_ComboBox.getSelectedItem().toString().equals(Bank2) )
        {
            Name_Label.setText("Name on Card");
            PIN_Label.setText("PIN");
            CardNo_Label.setVisible(true);
            CardNo_TextField.setVisible(true);
            Name_Label.setVisible(true);
       
            Name_TextField.setVisible(true);
            Name_TextField.setText("");
            Valid_Label.setVisible(true);
            Valid_ComboBox.setVisible(true);
            PIN_Label.setVisible(true);
            PIN_PasswordField.setVisible(true);
            PIN_PasswordField.setText("");
            
        }
        else
        {
            Name_Label.setText("NetBanking Username");
            Name_Label.setVisible(true);
            PIN_Label.setText("Password");
            Name_TextField.setVisible(true);
            Name_TextField.setText("");
            PIN_PasswordField.setVisible(true);
            PIN_PasswordField.setText("");
            PIN_Label.setVisible(true);
            CardNo_Label.setVisible(false);
            CardNo_TextField.setVisible(false);
            Valid_Label.setVisible(false);
            Valid_ComboBox.setVisible(false);
            
           
        }
        Proceed_Button.setText("Edit");
        Proceed_Button.setVisible(true);
        
        Pay_Button.setVisible(true);
        Message_Label.setVisible(false);
        
    }//GEN-LAST:event_Proceed_ButtonActionPerformed

    private void Pay_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pay_ButtonActionPerformed
        Message_Label.setVisible(true);
    }//GEN-LAST:event_Pay_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking_Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking_Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking_Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking_Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking_Confirmation().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CYB_ComboBox;
    private javax.swing.JLabel CYB_Label;
    private javax.swing.JLabel CardNo_Label;
    private javax.swing.JTextField CardNo_TextField;
    private javax.swing.JComboBox MOP_ComboBox;
    private javax.swing.JLabel MOP_Label;
    private javax.swing.JLabel Message_Label;
    private javax.swing.JLabel Name_Label;
    private javax.swing.JTextField Name_TextField;
    private javax.swing.JLabel PIN_Label;
    private javax.swing.JPasswordField PIN_PasswordField;
    private javax.swing.JButton Pay_Button;
    private javax.swing.JButton Proceed_Button;
    private javax.swing.JComboBox Valid_ComboBox;
    private javax.swing.JLabel Valid_Label;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
