/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nox;


import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Praneeth
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public static String get_username;
    public static String get_password;
    Statement s = null;
    ResultSet rs = null;
    int flag = 0;

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        username_field = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();
        signin = new javax.swing.JButton();
        register = new javax.swing.JButton();
        ForgotPassword_Label = new javax.swing.JLabel();
        Admin_Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);

        username.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        username.setForeground(new java.awt.Color(204, 204, 204));
        username.setText("Email ID");
        username.setToolTipText("Enter theusername");

        username_field.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N

        password.setFont(new java.awt.Font("Segoe UI Semibold", 1, 11)); // NOI18N
        password.setForeground(new java.awt.Color(204, 204, 204));
        password.setText("Password");

        signin.setText("Sign in");
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_registration_form(evt);
            }
        });
        signin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                signinKeyPressed(evt);
            }
        });

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        ForgotPassword_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        ForgotPassword_Label.setForeground(new java.awt.Color(192, 192, 192));
        ForgotPassword_Label.setText("Forgot Password ?");
        ForgotPassword_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgotPassword_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ForgotPassword_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ForgotPassword_LabelMouseExited(evt);
            }
        });

        Admin_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Admin_Label.setForeground(new java.awt.Color(204, 204, 204));
        Admin_Label.setText("Admin");
        Admin_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admin_LabelMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admin_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admin_LabelMouseEntered(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(192, 192, 192));
        jLabel1.setText("Tour >>");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_field, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ForgotPassword_Label))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Admin_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(642, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(signin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(register)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(111, 111, 111))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(549, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signin)
                    .addComponent(register)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ForgotPassword_Label)
                    .addComponent(Admin_Label))
                .addGap(48, 48, 48))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nox/cinemas/Background/background3.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(background, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        new Register().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_registerActionPerformed

    private void open_registration_form(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_registration_form
        get_username = username_field.getText();
        get_password = password_field.getText();
        
        if("".equals(get_username) && "".equals(get_password))
        {
            JOptionPane.showMessageDialog(null,"Email ID and Password cannot be empty");
        }
        else if("".equals(get_username))
        {
            JOptionPane.showMessageDialog(null, "Email ID cannot be empty");
        }
        else if("".equals(get_password))
        {
            JOptionPane.showMessageDialog(null, "Password cannot be empty");
        }
        else
        {
            try
            {
                DatabaseConnection con_1 = new DatabaseConnection();
                s = con_1.Connect.createStatement();
                rs = s.executeQuery("select * from customer where (email = '"+get_username+"')");
                while(rs.next())
                {
                    if(rs.getInt(8) == 0 && rs.getString(9).equals(get_password))
                        {
                            new Reset_Password().setVisible(true);
                            flag = 1;
                            dispose();
                        }
                    else if(rs.getString(9).equals(get_password)) {    
                            new Profile_1().setVisible(true);
                            dispose();
                            flag = 1;
                        }
                }
                if(flag == 0)
                {
                    JOptionPane.showMessageDialog(null, "Invalid Email ID or Password");
                    username_field.setText("");
                    password_field.setText("");
                }
                
            }
            catch(SQLException se)
            {
                JOptionPane.showMessageDialog(null,"Invalid Email ID or Password");
            }
            
        }

        
    }//GEN-LAST:event_open_registration_form

    private void ForgotPassword_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPassword_LabelMouseEntered
        ForgotPassword_Label.setForeground(Color.WHITE);
    }//GEN-LAST:event_ForgotPassword_LabelMouseEntered

    private void ForgotPassword_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPassword_LabelMouseExited
        ForgotPassword_Label.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_ForgotPassword_LabelMouseExited

    private void ForgotPassword_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPassword_LabelMouseClicked
        new ForgotPassword().setVisible(true);
        dispose();
    }//GEN-LAST:event_ForgotPassword_LabelMouseClicked

    private void Admin_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_LabelMouseEntered
        // TODO add your handling code here:
        Admin_Label.setForeground (Color.WHITE);
    }//GEN-LAST:event_Admin_LabelMouseEntered

    private void Admin_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_LabelMouseExited
        // TODO add your handling code here:
        Admin_Label.setForeground (Color.LIGHT_GRAY);
    }//GEN-LAST:event_Admin_LabelMouseExited

    private void Admin_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_LabelMouseClicked
        // TODO add your handling code here:
        new Admin_Login().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_Admin_LabelMouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jLabel1.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Profile_1_1 Tour_1 = new Profile_1_1();
        Profile_1_1.Logout_Label.setText("<< Login");
        Profile_1_1.Transactions_Label.setVisible(false);
        Profile_1_1.Profile_Label.setVisible(false);
        Profile_1_1.BookTickets_Label.setVisible(false);
        
        Tour_1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void signinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signinKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
        get_username = username_field.getText();
        get_password = password_field.getText();
        if("".equals(get_username) && "".equals(get_password))
        {
            JOptionPane.showMessageDialog(null,"Enter Username and Password");
        }
        else if("".equals(get_username))
        {
            JOptionPane.showMessageDialog(null, "Enter Username");
        }
        else if("".equals(get_password))
        {
            JOptionPane.showMessageDialog(null, "Enter Password");
        }
        
        else
        {
            try
            {
                DatabaseConnection con_1 = new DatabaseConnection();
                s = con_1.Connect.createStatement();
                rs = s.executeQuery("select * from customer where (email = '"+get_username+"')");
                while(rs.next())
                {
                    if(rs.getString(1).equals(get_username) && rs.getString(9).equals(get_password))
                    {
                        if(rs.getInt(8) == 0)
                        {
                            new Reset_Password().setVisible(true);
                            flag = 1;
                            dispose();
                        }
                        else{    
                            new Profile_1().setVisible(true);
                            dispose();
                            flag = 1;
                        }
                    }
                }
                if(flag == 0)
                {
                    JOptionPane.showMessageDialog(null, "Invalid Username or Password");
                    username_field.setText("");
                    password_field.setText("");
                }
                
            }
            catch(SQLException se)
            {
                JOptionPane.showMessageDialog(null,"Invalid Username or Password");
            }
            
        }
        }

    }//GEN-LAST:event_signinKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin_Label;
    private javax.swing.JLabel ForgotPassword_Label;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JButton register;
    private javax.swing.JButton signin;
    private javax.swing.JLabel username;
    private javax.swing.JTextField username_field;
    // End of variables declaration//GEN-END:variables
}
